server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
   # 就是和zookeeper的一样的
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

